name: cubeball
main: me.crylonz.CubeBall
version: 1.0.0
author: Crylonz, squi2rel, cloudfl4re
description: Play football in Minecraft
api-version: "1.21.11"
folia-supported: true
softdepend:
  - CraftEngine
  - emotecraft
  - BodySize
commands:
  ccb:
    description: Control command
    usage: /ccb [debug|glow|roll|setballhand|setballce|spawn|exitspawn|pause|resume|end|votepause]
permissions:
  cubeball.manage:
    description: Allows player to manage cubeball
    default: op
  cubeball.admin:
    description: Manage all match
    default: op
    children:
      cubeball.manage: true
  cubeball.timeout:
    description: Allows players to vote for a team timeout
    default: true
  cubeball.commandbypass:
    description: Allows players to bypass match and lobby command restrictions
    default: op
