name: cubeball
main: me.crylonz.CubeBall
version: 1.1.1
author: xWtree
contributors: [Crylonz, squi2rel, cloudfl4re]
website: https://github.com/mcxqk
description: 支持 Folia/Paper 1.21.11 的方块足球小游戏
api-version: "1.21.11"
folia-supported: true
softdepend:
  - CraftEngine
  - emotecraft
  - BodySize
  - Residence
commands:
  ccb:
    description: Control command
    usage: /ccb [help|input|join|check|reload|debug|glow|roll|redteam|blueteam|setballhand|setballce|spawn|exitspawn|pause|resume|end|votepause]
permissions:
  cubeball.manage:
    description: Allows player to manage cubeball
    default: op
  cubeball.admin:
    description: Manage all match
    default: op
    children:
      cubeball.manage: true
  cubeball.timeout:
    description: Allows players to vote for a team timeout
    default: true
  cubeball.commandbypass:
    description: Allows players to bypass match and lobby command restrictions
    default: op
