name: cubeball
main: me.crylonz.CubeBall
version: 1.0.0
author: Crylonz, squi2rel
description: Play football in Minecraft
api-version: "1.21.11"
folia-supported: true
softdepend:
  - CraftEngine
commands:
  ccb:
    permission: cubeball.manage
    description: Control command
    usage: /ccb
permissions:
  cubeball.manage:
    description: Allows player to manage cubeball
    default: op
  cubeball.admin:
    description: Manage all match
    default: op
